Create TABLE IF NOT EXISTS users
(
    id         MEDIUMINT NOT NULL AUTO_INCREMENT,
    name       CHAR(30)  NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

